trigger:
 - master
pool:
 name: local
 demands: 
 - Agent.Name -equals amazonliux
stages:
  - stage: Build
    jobs:
    - job:
      steps:
       - script: echo "Build Stage"
  - stage: Test
    jobs:
    - job:
      displayName: 'This is a stage Job1'  
      steps:
      - script: echo "Test Stage"
    - job: 
      displayName: 'This is a stage 2nd job'
      steps:
        - script: echo " Test stage job2"
  - stage: Deploy
    condition: failed()
    jobs:
    - job: 
      steps:
      - script: echo "Deploy to Prod"    
